# Generated by Django 4.0.4 on 2022-07-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='poetry2',
            fields=[
                ('poetrys_id', models.IntegerField(primary_key=True, serialize=False)),
                ('poetrys', models.CharField(max_length=1000)),
            ],
        ),
    ]
